### PR TITLE
implement hotspot attribute in dragging

### PR DESCRIPTION
**Pull request by tillbey**
Well, I'm not sure you are ready to add features. But the original repo at nucleic is so far behind..
This is to enable "tearing" of a widget while dragging: so the cursor is on the pixmap where it appeared on the widget. This can be overidden with a new "hotspot" attribute.

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
I wish I could get my work merged into the original repo but @sccolbert is not responsive lately. So I may start considering adding new features... I am not familiar with the concept of hotspots, do you care to enlighten me ?

**Comment by tillbey** [comment]
Yes, I got that feeling. The hotspot is basically the point in the pixmap that is directly under the cursor. By default it is the left upper corner (0, 0) in the enaml's Qt implementation. This leads to an ugly jump, though, if you drag a away a widget (while hiding it at the same time).
hotspot_at_0 0

I suggest to have as default (i.e. an empty tuple as attribute) the pixmap appearing under the cursor the same as the original widget. This calculated by getting the cursor position, then making it relative to widget coordinates.
hotspot_under_cursor

Like this you can nicely tear of a widget. Let me know what you think.

**Comment by MatthieuDartiailh** [comment]
This looks really good ! I will try to find some time to test it myself before merging. Do not hesitate to ping me if I take more than a week.

**Comment by MatthieuDartiailh** [comment]
Testing this I uncovered a bug in the related example and in the parser (fixed by #19 and #18). If you can give those a look, it would be great. 
Once those two are merged I will merge this one as my tests both on Python 2 and 3 have been conclusive.

**Comment by MatthieuDartiailh** [comment]
Thanks @tillbey

**Pull request merged**
